packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.0.6
  react: ^19.0.0
  react-dom: ^19.0.0
  zod: ^3.25.74
  tsx: ^4.20.3
  typescript: ^5.8.3
  wrangler: ^4.23.0
  '@cloudflare/workers-types': ^4.20250705.0
  '@types/node': ^22.16.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  drizzle-kit: ^0.31.4
  alchemy: ^0.43.5
  http-status-codes: ^2.3.0
  dotenv: 16.5.0
  drizzle-orm: ^0.44.2
  drizzle-seed: ^0.3.1
  drizzle-zod: 0.8.2
  concurrently: ^9.2.0
  wait-on: ^8.0.3
