name: "Release Version"

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
